---
fontsize: 12pt
geometry: margin=1in
header-includes: 
- \usepackage{multirow} 
output:
  html_document:
    df_print: paged
  pdf_document:
    fig_caption: yes
    keep_tex: yes
    number_sections: no
editor_options: 
  chunk_output_type: console
---




```{r, echo=FALSE}
htmltools::img(src = knitr::image_uri(file.path('images/QuEST_logo.png')), 
               alt = 'logo',
               width = "400",
               style = 'float: right; top:0; right:0; padding:10px;')
```



# Foundations of Quantitative Reasoning (BIO381)

-------

# Syllabus and Course Outline

University of Vermont

Fall 2019

Instructor: __Dr. Easton R. White__

email: Easton.White@uvm.edu

Class Time: M/W/F 1:10-3:00pm, Location TBD 

Office hours: Time: TBD, Location: Jeffords 347
 


# Course Introduction

Welcome to the [QuEST](https://www.uvm.edu/quest) Foundations of Quantitative Reasoning course. There are no specific prerequisites for this course, but students should have some experience programming in R, using Github, and with basic math and statistics. This course is designed to provide students with a solid background in both ecology and evolution as well as commonly used quantitative tools. By the end of the course, students should be able to:

### Concepts 
1. Understand basic concepts in population and community ecology
2. Compare and contrast different modeling philosophies
3. Analyze simple population models using qualitative approaches
4. Use linear algebra to construct and analyze structured population models
5. Understand foundations of spatial ecology and build simple models
6. Compare and contrast hypotheses that attempt to explain basic patterns in biodiversity.
7. Understand principles of evolution and natural selection
8. Understand and apply various tools to understand evolution (population genetics, quantitative genetics, and game theory)
9. Understand and apply simple models to study infectious disease dynamics 
10. Describe how humans affect ecological and evolutionary dynamics


### Skills

11. Read and discuss papers that involve modeling
12. Construct and program simple population models in R
13. Understand and apply a variety of mathematical tools (equilibrium and stability analysis, linear algebra, stochastic models, etc.)
14. Work in small, collaborative groups to find solutions to particular case studies.
15. Apply basic pedagogy principles in designing a lesson


This is clearly a lot of concepts and skills to cover in one semester. However, there will be lots of time to ask questions and to have discussions. The format of the class will change from day to day, but will include a combination of lecturing, problem-solving activities, discussions, and working in small groups. 

You should be able to complete most assignments within the allotted class-time, but plan to spend a couple of hours each week outside of class reading papers and finishing assignments. The more time and effort you put in, the more you will get out of this course. 

Any and all of the content of this syllabus is subject to change as we go through the course. The material will be tailored to fit the needs of the class. Changes will be announced in-class and electronically. 
 

# Course resources

#### Your classmates

By its very nature, this course will challenge each student during different points. The ecology and evolution may be challenging for those with little biology background and the quantitative skills may be difficult to pick up for those of you with traditional biology backgrounds. It will be essential to work with others on assignments---just be sure that you understand the material yourself.

#### Your instuctor

I will hold office hours several times per week (time to be determined) and I am always happy to set up additional times to meet. Please ask for help, early and often. If you have a question, others in the class surely have the same one. There will be several opportunities to provide formal feedback on the course, but at any point, please reach out to let me know how I might improve the course. Email is the best way to get a hold of me. You can expect a response within 24 hours except on weekends and holidays when I do not check my email.

 

#### Various textbooks

This course will not follow any particular textbook. However, I will draw from several books and online sources:

* [Graham Coop's population genetics notes](https://github.com/cooplab/popgen-notes)
* [Gotelli, Nicholas J. A primer of ecology. No. 577.88 G6. Sunderland, Massachusetts, USA: Sinauer Associates, 2008.
](https://www.amazon.com/Primer-Ecology-Fourth-Nicholas-Gotelli/dp/0878933182/ref=pd_bbs_sr_1?ie=UTF8&s=books&qid=1231604546&sr=8-1)
* [Hastings, Alan, Population biology: concepts and models. Springer Science & Business Media, 2013.](https://www.amazon.com/Population-Biology-Concepts-Alan-Hastings/dp/0387948538)
     
#### Various online tools

Calculus a bit rusty? Maybe you're not totally remembering Mendelian genetics? Something else? We will walk through topics from the beginning, but there might be points that still seem confusing. Besides your classmates and instructor, there are a plethora of online tools to help provide a quick refresher: 

* [Paul's Online Notes](http://tutorial.math.lamar.edu/)
* [Khan Academy](https://www.khanacademy.org/)
* [Software Carpentry computational tools material](https://software-carpentry.org/lessons/)
  


# Grading Standards and Practices

#### Problem sets: 10 @ 5 points each

Every week there will be assigned problem sets. These will involve a mix of math done on paper and programming in R. The problem sets will either be turned in on paper or on Github depending on the assignment. Some problem sets will be individual-based and others will be in small teams.

#### Group project: 25 points 

The final project will involve building a model to understand some system. The choice of system, modeling approach, and question will be up to each team. The teams will be between 2-3 students. Think of this project as an opportunity that could lead to a publication. More details will be given in class.


#### Participation: 25 points

Students will be expected to be engaged each class period. This will involve participating in discussions and group activities.






# Academic honesty

Students in the class are expected to complete their own work. It is encouraged that you work with other students outside of class, but your completed work must be from you and in your own words. Students are expected to follow UVM policy on plagiarism, fabrication, collusion, and cheating: http://www.uvm.edu/policies/student/acadintegrity.pdf.







# Student Learning Accomadations

In keeping with University policy, any student with a documented disability interested in utilizing accommodations should contact SAS, the office of Disability Services on campus. SAS works with students and faculty in an interactive process to explore reasonable and appropriate accommodations, which are communicated to faculty in an accommodation letter. All students are strongly encouraged to meet with their faculty to discuss the accommodations they plan to use in each course. A student's accommodation letter lists those accommodations that will not be implemented until the student meets with their faculty to create a plan. Contact SAS: A170 Living/Learning Center; 802-656-7753.

Contact Student Accessibility Services (SAS):

* A170 Living/Learning Center
* 802-656-7753
* access@uvm.edu
* https://www.uvm.edu/academicsuccess/student_accessibility_services









# Student health and wellbeing

There are several resources on campus dedicated to promoting student health and well-being, including:

* Center for Health and Wellbeing https://www.uvm.edu/health

* Counseling & Psychiatry Services (CAPS) https://www.uvm.edu/health/CAPS


<!--
# Code of Civility

All students are expected to adhere... 


## Sexual harassment

Sexual harassment includes any unwelcome verbal or physical conduct of sexual nature 
-->


