---
editor_options:
  chunk_output_type: console
output:
  html_document: null
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

2019

BIO 381: Foundations of Quantitative Reasoning

**Assignment: Final project** 

Easton White

___


# Introduction

The capstone assignment of this course is a group project. Most of the work will be done during the second half of the semester. Groups will consist of 2-3 students and should include a mix of those with biology and those with mathematical/programming backgrounds. Project ideas can include anything that involves the use of mathematical models. Specific topic choices will be submitted and approved by the instructor. Ideally, projects will focus on interesting problems that could for the basis of a thesis chapter or manuscript. This capstone should be viewed as an opportunity to explore an interesting topic---not simply a class assignment. These could be based on student research interests or case studies developed in class.

This assignment has several small deadlines, but will culminate with a written document and presentation. 


# Timeline

Date          | Assignment     | Points
-------       | ----------------------------------------------  | ----------
4-Mar         | Choose teams and submit topic via email | 1 point
24-Apr        | Submit draft write-up for feedback | 4 points
1-May         | Submit final draft incorporating feedback | 20 points
1-May         | Short (15 min) presentation about your findings to the class | 5 points


# Grading rubric

The final write-up will be assessed on its scientific merit, use of appropriate methods, and writing. The write-up should be in the format of a traditional scientific manuscript, but it does not need to be as detailed or extensive. The grading breakdown is as follows:

Item | Points
----------------------------------------------  | ----------
Use of methods/approaches developed in this course (i.e. a mathematical modeling aspect of the project) | 5 points
Appropriate organization of text (abstract, introduction with motivation of scientific question, methods, results/discussion) and clarity of writing | 10 points
Presentation of the project (R markdown including both .Rmd and pdf versions, figures) | 5 points



